### ISSUE TITLE
Update homepage log in button text if I'm already logged in

### ISSUE THREAD

**Issue by maya** [18F/federalist#1641] opened 2018-02-20 22:23 UTC
If I'm already logged in to Federalist and I visit the homepage, the button still says "Log in." 

Some options:
- Maybe this should say "Go to app" instead?
- Maybe it should redirect me to the app instead?

**Comment by jseppi** [comment] 2018-02-20 22:53
If you are logged in, there shouldn't be a way for you to get to the home page. Rather, you should immediately be redirected to `/sites`.

Is this not happening? I'm not able to reproduce.

**Comment by jseppi** [comment] 2018-02-20 22:56
Maybe this is what is happening:

When you arrive to the front page and are presented with the "Log in" button, that means your session has ended and you are not logged-in (ie, any actions taken with your current Federalist cookie will not work).

When you click "Log in," even though it seems be be doing nothing other than redirecting to you to `/sites`, it's actually re-checking the authorization with GitHub and starting a new session.

**Comment by wslack** [comment] 2018-02-22 22:57
@maya is this reproducible? The redirect should take care of things generally.

**Comment by maya** [comment] 2018-02-22 23:22
It happens every time if that's what you're asking. @jseppi's assessment of what was happening seems correct.

**Comment by wslack** [comment] 2018-02-23 20:33
Is this the right workflow?

1. Log into Federalist
2. Navigate elsewhere
3. Return to https://federalist.18f.gov same day
4. Can't see the list of sites
5. Still have to click "log in"

**Comment by maya** [comment] 2018-02-23 20:53
Yes, that's my experience of using Federalist, can't speak to how others use it. 

"same day" can be literally one second after, it's the same result.

**Comment by jseppi** [comment] 2018-02-23 20:56
Oh wow, that it happens immediately is definitely not supposed to be the case :\ I'm not able to reproduce that either.

Are you closing your browser completely? That will also wipe your auth session.

**Comment by maya** [comment] 2018-02-23 20:59
No, I'm not, just opening a new tab.

**Comment by jseppi** [comment] 2018-02-23 21:02
Hrm, are you by chance going to `https://federalist.fr.cloud.gov` instead of `https://federalist.18f.gov`?

**Comment by maya** [comment] 2018-02-23 21:03
I am! That's what I was told was the federalist homepage previously.

**Comment by jseppi** [comment] 2018-02-23 21:05
Woohoo! Solved :) That's the internal cloud.gov URL, but the 18f.gov one is the "real one."
I think at some point in the past we did use the `.fr.cloud.gov` URL and you've been a Federalist user for so long that you were probably directed to use it back then. Apologies for the trouble!

**Closed** 2018-02-23 21:06 UTC

**Comment by wslack** [comment] 2018-02-24 03:06
@maya there was an announcement to use the 18f address way on back but we left the old one up. This makes me think we should turn it into an HTML redirect to ask people to reset their bookmarks.
