### ISSUE TITLE
Planning shutdown of federalist.18f.gov and LTS of DNS

### ISSUE THREAD

**Issue by jcscottiii** [18F/federalist#920] opened 2017-05-17 21:54 UTC
In order to migrate Federalist off of the cloud.gov E/W env, we need to make sure federalist.18f.gov is transitioned or shut down properly.

Currently, there are two web hooks. One for the E/W env which is federalist.18f.gov and one for the govcloud env federalist.fr.cloud.gov.

We can't simply point the DNS to the new environment because then there would be redundant builds.

This issue is to discuss the possibilities to do this successfully.

@jmhooper @wslack

**Comment by jmhooper** [comment] 2017-05-17 22:14
Here's a list of sites on GovCloud for which we don't have an access token that can update webhooks: https://drive.google.com/a/gsa.gov/file/d/0B6Xbcsx20HbHMGVWckdsSXN6S0k/view?usp=sharing

**Comment by wslack** [comment] 2017-05-18 02:42
Update: it appears that GovCloud and old Federalist have different secrets, so we won't have issues with the old webhooks (though I don't like the tech debt of leaving them there)

**Comment by jcscottiii** [comment] 2017-05-18 16:59
@wslack does that update influence the timeline of when we can transition the DNS?

**Comment by wslack** [comment] 2017-05-18 18:20
@jcscottiii only in that I want to set the plan then announce it with a few days warning, so the longer this convo takes, the longer it will take to shut down.

**Comment by wslack** [comment] 2017-05-22 19:37
Update: plan is to turn off E/W on Thursday, probably?

**Comment by jmhooper** [comment] 2017-05-22 21:15
:+1: for Thursday

**Comment by wslack** [comment] 2017-05-23 19:56
Are we going to try to have federalist.18f.gov start serving the current app at federalist.fr.cloud.gov on Thursday?

**Comment by jcscottiii** [comment] 2017-05-23 20:36
@jmhooper ?  ^ Let me know if there's something you need on my side if you do want to try that

**Comment by jmhooper** [comment] 2017-05-25 16:46
Here is the plan for Tomorrow AM:

1. Backup E/W postgres instance
1. Shutdown E/W apps and services
1. Point federalist.18f.gov at federalist.fr.cloud.gov
1. Update Federalist's environment variables so it is aware it is being served on federalist.18f.gov
1. Update GH Oauth application with new redirect URL (we will need a GH Admin for this; can we have one standing by?)
1. Run a script that deletes all of our sites's old webhooks and generates new ones for federalist.18f.gov
1. Done 🎉 

Sites with webhooks that still point at federalist.fr.cloud.gov _should_ still work since the app is still being served there. Sites with webhooks pointed at federalist.18f.gov expecting the old E/W app _should not_ work since now their webhook secret will be invalid.

**Comment by wslack** [comment] 2017-05-25 18:03
Can the script for #6 create the new webhooks first so we can confirm they worked, before we delete anything?

**Comment by jmhooper** [comment] 2017-05-25 18:04
Yeah, we can comment out the part that deletes the webhooks.

**Comment by jseppi** [comment] 2017-05-25 18:16
Can the deletion of E/W apps and services (current step 2) happen _after_ the switchover is complete and confirmed to be working?

**Comment by jmhooper** [comment] 2017-05-25 18:18
And I think it is a good idea to switch everything over before fully tearing down the old app.

**Comment by wslack** [comment] 2017-05-25 18:25
Confirmed; let's reorder the steps. Also, we should do https://github.com/18F/pages-redirects/issues/88 first. @jseppi think you can handle this issue (billing it to the internal project you used in building that app?)

**Comment by jseppi** [comment] 2017-05-25 18:31
Sure thing.

**Comment by jseppi** [comment] 2017-05-25 19:30
PR ready: https://github.com/18F/pages-redirects/pull/89/files

**Closed** 2017-05-26 17:40 UTC
