### ISSUE TITLE
500 Error when updating repo in site settings

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#1732] opened 2018-03-23 20:18 UTC
#### Description of feature or bug
Steps taken by reporter (Eddie Tejeda):

1) had an existing site on Federalist
2) changed github repo name
3) attempted to add new repo with new name to Federalist
4) received 500 ERROR multiple times
5) 3rd or 4th attempt, the workflow worked and the build screen said the build had been underway for 5 minutes.

#### Definition of done

We know why this happened and can or cannot reproduce.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by wslack** [comment] 2018-03-23 23:07
@amirbey edited your original text and moved to *ready* for you to pick up an see if you can reproduce next week. (bonus: see if you can enable detailed logging while you try to replicate the workflow - @jmhooper or @el-mapache can help with that?)

https://docs.google.com/document/d/1EqS9BU4O-8OfSKa_aTyddYPk4TYHyLWj7r8L3LDE2AQ/edit

But, I think we'll need to get you  prod access before you can run the logs.

**Comment by wslack** [comment] 2018-03-29 23:19
Hmm. We definitely didn't get the error when using the old repo name.; I'm not sure this re-creation is fully applicable.

If we can't validate it, maybe a one-time fluke? It did eventually work.

**Comment by wslack** [comment] 2018-03-30 16:39
Moving back to icebox since we can't replicate.

**Comment by wslack** [comment] 2018-05-21 15:10
Closing as we couldn't replicate @eddietejeda's report! Will revisit if reported again.

**Closed by wslack** 2018-05-21 15:10 UTC
