### ISSUE TITLE
Can't deploy staging to GovCloud

### ISSUE THREAD

**Issue by el-mapache** [18F/federalist#559] opened 2016-10-21 19:50 UTC
This issue is arose when trying to deploy the staging configuration with the node devDependencies.

When doing a cf push without uploading node_modules, the build process was running out of disk space.

```
cp: cannot create regular file ‘/tmp/contents354112921/app/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-function-name/node_modules/babel-helper-function-name/node_modules/babel-traverse/node_modules/lodash/fp/times.js’: No space left on device
```

Cloud Foundry has a 1 GB limit on application uploads, it has a 2 GB disk space limit for a running app (It's not clear what limit is enforced in a build process) https://docs.cloudfoundry.org/devguide/deploy-apps/large-app-deploy.html

Attempting to build locally before pushing resulted in the following error:

```
       > fsevents@1.0.14 install /tmp/app/node_modules/fsevents
       > node-pre-gyp install --fallback-to-build

       node-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v46-linux-x64.tar.gz
       node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@4.2.3 (node-v46 ABI) (falling back to source compile with node-gyp)
       gyp ERR! UNCAUGHT EXCEPTION
       gyp ERR! stack Error: Cannot find module 'es5-ext/string/#/contains'
       gyp ERR! stack     at Function.Module._resolveFilename (module.js:337:15)
       gyp ERR! stack     at Function.Module._load (module.js:287:25)
       gyp ERR! stack     at Module.require (module.js:366:17)
       gyp ERR! stack     at require (module.js:385:17)
       gyp ERR! stack     at Object.<anonymous> (/tmp/app/node_modules/d/index.js:6:21)
       gyp ERR! stack     at Module._compile (module.js:435:26)
       gyp ERR! stack     at Object.Module._extensions..js (module.js:442:10)
       gyp ERR! stack     at Module.load (module.js:356:32)
       gyp ERR! stack     at Function.Module._load (module.js:311:12)
       gyp ERR! stack     at Module.require (module.js:366:17)
       gyp ERR! stack     at require (module.js:385:17)
       gyp ERR! System Linux 4.4.0-42-generic
       gyp ERR! command "/tmp/app/.heroku/node/bin/node" "/tmp/app/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/tmp/app/node_modules/fsevents/lib/binding/Release/node-v46-linux-x64/fse.node" "--module_name=fse" "--module_path=/tmp/app/node_modules/fsevents/lib/binding/Release/node-v46-linux-x64"
       gyp ERR! cwd /tmp/app/node_modules/fsevents
       gyp ERR! node -v v4.2.3
       gyp ERR! node-gyp -v v3.4.0
       gyp ERR! This is a bug in `node-gyp`.
       gyp ERR! Try to update node-gyp and file an Issue if it does not help:
       gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
       node-pre-gyp ERR! build error
       node-pre-gyp ERR! stack Error: Failed to execute '/tmp/app/.heroku/node/bin/node /tmp/app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/tmp/app/node_modules/fsevents/lib/binding/Release/node-v46-linux-x64/fse.node --module_name=fse --module_path=/tmp/app/node_modules/fsevents/lib/binding/Release/node-v46-linux-x64' (7)
       node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/app/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
       node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
       node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
       node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
       node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
       node-pre-gyp ERR! System Linux 4.4.0-42-generic
       node-pre-gyp ERR! command "/tmp/app/.heroku/node/bin/node" "/tmp/app/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
       node-pre-gyp ERR! cwd /tmp/app/node_modules/fsevents
       node-pre-gyp ERR! node -v v4.2.3
       node-pre-gyp ERR! node-pre-gyp -v v0.6.29
       node-pre-gyp ERR! not ok
       Failed to execute '/tmp/app/.heroku/node/bin/node /tmp/app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/tmp/app/node_modules/fsevents/lib/binding/Release/node-v46-linux-x64/fse.node --module_name=fse --module_path=/tmp/app/node_modules/fsevents/lib/binding/Release/node-v46-linux-x64' (7)

       npm ERR! Linux 4.4.0-42-generic
       npm ERR! argv "/tmp/app/.heroku/node/bin/node" "/tmp/app/.heroku/node/bin/npm" "rebuild"
       npm ERR! node v4.2.3
       npm ERR! npm  v2.15.9
       npm ERR! code ELIFECYCLE
       npm ERR! fsevents@1.0.14 install: `node-pre-gyp install --fallback-to-build`
       npm ERR! Exit status 1
       npm ERR!
       npm ERR! Failed at the fsevents@1.0.14 install script 'node-pre-gyp install --fallback-to-build'.
       npm ERR! This is most likely a problem with the fsevents package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     node-pre-gyp install --fallback-to-build
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs fsevents
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!
       npm ERR!     npm owner ls fsevents
       npm ERR! There is likely additional logging output above.

       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/app/npm-debug.log
-----> Build failed
```

By deleting the fsevents module locally and re pushing the app, we were able to successfully deploy.  The theory is that omitting this module forced it to be built on the server with the correct version for the server buildpack.

**Comment by rogeruiz** [comment] 2016-10-24 16:34
@el-mapache @jbarnicle Is this resolved? Can we please document the resolution even if it pointing to Slack channels to start. These docs will be invaluable for migrating other users with complicated deployments.

**Comment by el-mapache** [comment] 2016-10-24 16:48
I would not say this issue is resolved. The workaround involves manually deleting a specific node module in order to avoid a bug with another node module. It would be great to find a solution that didn't require hard coding this specific workaround.

Additionally, this app still has the issue of running out of disk space. As more dependencies are added, the problem will occur again.

Interestingly, installing node modules on the cloud foundry server takes up ~750mb of disk space, while installing the dependencies locally uses ~ 240mb of disk space. This seems to indicate that cloud foundry (or the node js buildpack?) is not properly cleaning up after itself.

**Comment by rogeruiz** [comment] 2016-10-24 16:56
Interesting point on the disk space discrepancy. That'd be a good thing to look into here @jbarnicle.

@el-mapache I think it's important to document that manually deletion of specific `node_modules` along with the reason. You could just point to this issue as we'll be keeping it up-to-date.

**Comment by jbarnicle** [comment] 2016-10-24 17:32
@rogeruiz At the very end of the issue I mention that we manually deleted the fsevents module in order to force it to be built on the server.  I can try to better document why exactly that worked.

@el-mapache Can you dive a little deeper into documenting the discrepancies between the local dependency build of ~240MB and the one on the server ~750MB.  It might help diagnose where the problem lies.  If it's specific to a few node modules it might help in searching for answers.

**Comment by rogeruiz** [comment] 2016-10-24 17:41
Thanks @jbarnicle I'd say let's create a `DEPENDENCIES.md` file and link from the `README.md` about this and have it in there. The issue is useful for tracking the work, but we need something in the repository to live alongside the code.

**Comment by el-mapache** [comment] 2016-10-24 18:01
@jbarnicle I'm not sure where to start with that, unfortunately. I don't know how to mimic the conditions under which the modules install. I only know that when the app boots up at the end of the build process, pre-pushing the node modules gives me a '241mb out of 2G' and building on the server gives something like '741mb out of 2GB'.

I guess if we knew exactly how the containers worked on cloud foundry / gov cloud a local container system could be set up to run the buildpack.

**Comment by jbarnicle** [comment] 2016-10-24 18:29
@el-mapache Digging thru some of the node.js documentation on cloud foundry.  Do you know if we are vendoring our dependencies?

https://docs.cloudfoundry.org/buildpacks/node/index.html#vendoring

**Comment by jbarnicle** [comment] 2016-10-24 20:00
@rogeruiz @el-mapache Since CF recommends that you vendor the dependencies before pushing, I'm not sure there is much else to do with this issue other than create the `Dependencies.md` and link to it from the `Readme.md`.  Can you do that @el-mapache - I think you have a firmer grasp of the node.js implications?

@rogeruiz Do you have any recommendations on a deploy process that could achieve the above without having to actually having to check them into Git?

**Comment by el-mapache** [comment] 2016-10-26 15:00
@jbarnicle Sure, we can just make a note of the step that needs to happen. Its not hard to add the deletion of the `fsevents` modules to the travis config file.

Thanks!

**Comment by wslack** [comment] 2016-11-01 17:42
This was done. This was a temp issue for visibility. Full fix is in https://github.com/18F/federalist/pull/579

**Closed by wslack** 2016-11-01 17:42 UTC
Labels: help wanted
