### ISSUE TITLE
Bug with loading yml files

### ISSUE THREAD

**Issue by dhcole** [18F/federalist#242] opened 2015-12-07 23:36 UTC
@jeremiak just noticed this error, which I think is related to the image PR. If you try to open a file like `_config.yml` in the editor, you get an error like the following:

Not sure if this is related to our code or the Prosemirror update. What do you think?

<img width="356" alt="screen shot 2015-12-07 at 6 35 08 pm" src="https://cloud.githubusercontent.com/assets/170641/11643353/5cb5db72-9d11-11e5-9468-7f2cf3626c8c.png">
<img width="428" alt="screen shot 2015-12-07 at 6 35 18 pm" src="https://cloud.githubusercontent.com/assets/170641/11643354/5e406570-9d11-11e5-9fcd-e223f7167d2b.png">

**Comment by jeremiak** [comment] 2015-12-08 05:19
I actually think this is an older bug that we hadn't caught yet. 

Question: What is expected behavior when you open a file that is just YML, such as `_config.yml`? Do you see both the prosemirror editor (blank since there is no content), or do you just see the code mirror editor with the yaml?

Diagnosis: What seems to be happening is that when you try and open a `.yml` file in the editor, it just uses the settings (codemirror) editor and tries to pass `false` as the value to the content (prosemirror) editor. The reason the content of a document is set to false is based on the assumption that if you're editing a `.yml` file you won't be adding any sort of markdown whatsoever.

**Closed** 2015-12-10 16:53 UTC
Labels: in progress
