### ISSUE TITLE
Possible to have "crossed" GitHub logins

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#952] opened 2017-05-31 15:10 UTC
1. Log in to GitHub account A
1. Log in to Federalist
1. Log out of GitHub account A
1. Log in to GitHub account B
1. Federalist still thinks you are in GitHub account A, and you won't be able to log out or do other actions

cc @wslack: I think this describes how to get into at least one of the weird states we saw while in the video call attempting to debug Chris's Add Site problem

**Comment by jmhooper** [comment] 2017-06-09 15:03
This looks like it was caused by #978 and CloudFront caching the response from `/v0/me`. #976 should have a fix.

**Comment by jmhooper** [comment] 2017-06-09 15:05
Moving this to in progress, because #976 only fixes the issue with logging out.

I'm not sure if we want to do something about changing Federalist users when a user logs out of GitHub. I don't see a clear path besides shorter session times, but appreciate any suggestions?

**Comment by wslack** [comment] 2017-06-09 18:20
I'm ok with Github logouts causing everything to break. I wouldn't want users to be using the wrong login by accident.

**Comment by jmhooper** [comment] 2017-06-09 19:04
The problem is I don't think we can determine who is logged into GitHub without asking the user to re-authorize.

**Comment by jseppi** [comment] 2017-06-09 19:06
What about periodically checking the auth with the OAuth refresh token?

**Comment by jmhooper** [comment] 2017-06-09 19:08
The GitHub access token will remains valid after the user logs out of GitHub. So it doesn't tell us if the user is logged in.

Regardless though, it may be a good idea to purge sessions of users associated with an invalid auth token.

**Comment by jseppi** [comment] 2017-06-09 19:11
Oh yeah, that way if a user becomes de-authorized (like by getting removed from the GitHub org), the app will also de-auth them in a timely manner.

**Comment by jmhooper** [comment] 2017-06-09 19:12
Yeah, we've traditionally relied on the session expiration to handle that

**Comment by wslack** [comment] 2017-06-09 20:43
This is not an issue. :gavel:

**Closed by wslack** 2017-06-09 20:43 UTC
Labels: bug, question
