### ISSUE TITLE
Federalist doesn't appear to support error pages

### ISSUE THREAD

**Issue by gemfarmer** [18F/federalist#338] opened 2016-04-06 16:54 UTC
@jeremiak, I made [404 and 500 error pages](https://github.com/18F/doi-extractives-data/issues/1206#issuecomment-206460286) for the [EITI site](https://useiti.doi.gov), but they don't appear to be working within Federalist. They trigger properly locally within our Jekyll framework, so it seems most likely that Federalist doesn't support them. Are you aware of any instances where people have added error pages within Federalist?

**Comment by jeremiak** [comment] 2016-04-06 20:19
I don't think Federalist is currently set up to handle this, but I think I know how we can. According to the [AWS CLI documentation](http://docs.aws.amazon.com/cli/latest/reference/s3/website.html) I need to change the `error-document` value for the site.

Let me give it a shot and see how difficult it ends up being.

**Comment by gemfarmer** [comment] 2016-04-06 21:01
Sweet! 

```--error-document (string) The object key name to use when a 4XX class error occurs.```

I assume this means something different might need to be done for 500 errors??

**Comment by jeremiak** [comment] 2016-04-06 21:32
What exactly would a 500 error look like on a static site? Or rather, what sequence of events might lead a user to a 500 error?

**Comment by gemfarmer** [comment] 2016-04-06 21:36
yeah 404 is the more important issue. We are adding sql-lite, so it might end up being an issue for us, but for now 404 is more than enough

**Comment by leahbannon** [comment] 2016-06-22 22:44
duplicate of #307

**Closed by leahbannon** 2016-06-22 22:44 UTC
