### ISSUE TITLE
Interface for rebuilding sites

### ISSUE THREAD

**Issue by dhcole** [18F/federalist#163] opened 2015-09-14 02:50 UTC
In case things go wrong, we should have an admin interface to simplify rebuilding a given site, perhaps to at given commit SHA, as well as an option to rebuild all sites at their latest commit for a disaster scenario of the S3 bucket disappearing.

**Comment by wslack** [comment] 2016-10-20 16:08
Closing as duplicate of https://github.com/18F/federalist/issues/523

**Closed** 2016-10-20 16:08 UTC
