### ISSUE TITLE
Modify Federalist config to serve index.xml from its parent directory

### ISSUE THREAD

**Issue by thisisdano** [18F/federalist#1220] opened 2017-10-05 21:32 UTC
DigitalGov has feeds that live at a URLs like `https://digitalgov.gov/feed/index.xml` that we'd like to load from "pretty" URLs like `https://digitalgov.gov/feed/` — _primarily_ for backward compatibility with our existing (Sites) feed location. 

**Example:**
Existing feed: https://digitalgov.gov/feed/
Federalist feed (on our demo branch): https://demo.digitalgov.gov/feed/index.xml
☝️ _We'd like the Federalist feed URL to match the existing URL._

@jseppi has indicated that this could be done through an nginx config on S3 that would apply to all  Federalist-hosted sites. 

> I think that would require modifying the `index` directive in `federalist-proxy` to serve `index.xml`. It defaults to serving files named `index` or `index.html`.
>
> ref: http://nginx.org/en/docs/http/ngx_http_index_module.html#index
>
> And I think there'd be more nginx configuration necessary to get the response `content-type` to be what you probably want (`application/rss+xml`)

**So, some questions as we consider this:**
- What would it take to make this change? 
- What would we need to discuss? 
- How soon could it happen? 
- What would be the possible implications? 

It's important to us to move forward without breaking our feeds, but I'd like to understand the implications of the kind of change proposed.

**Comment by jseppi** [comment] 2017-10-05 21:35
The seems like it would not impact any sites that are using feeds by full path because they'd still be able to access it by full path (ie, it would be backwards compatible).

**Comment by wslack** [comment] 2017-10-05 22:14
@jseppi there's no way to do this but by modifying the proxy?

**Comment by jseppi** [comment] 2017-10-05 22:15
Not that I'm aware of.

**Comment by wslack** [comment] 2017-10-05 22:17
Why can't the build system put the content at the other URL?

**Comment by jseppi** [comment] 2017-10-05 22:29
Will that work? The builder would have to put the content at the S3 key `.../feed/` instead of `.../feed/index.xml`.

@jmhooper?

**Comment by jseppi** [comment] 2017-10-05 22:33
I'm actually fairly sure S3 could make such a key, but that would be kind of a bizarre case for the publish script to handle, in my opinion.

**Comment by jeremyzilar** [comment] 2017-10-06 17:20
I would like to point out that as other sites from OPP/SITES migrate over from WordPress to Federalist, this might be a need for WP sites with RSS feeds. They all have feed urls at `/feed/`.

**Comment by wslack** [comment] 2017-10-06 17:33
Let's see what @jmhooper says. @jeremyzilar there are ATO implications to changing the proxy so I want that to be a last resort only.

**Comment by wslack** [comment] 2017-10-06 17:34
Does the file have to be named .xml? Seems like the existing proxy would serve it without the file name.

**Comment by thisisdano** [comment] 2017-10-11 14:21
I don't think we can output the file without an extension.
Any other thoughts on this issue or ways forward? We're preparing to launch this site and this is one of the last items without closure.
cc @jeremyzilar

**Comment by wslack** [comment] 2017-10-11 16:46
We discussed more this AM and I think we can move on this. We'll work on that this or next sprint.

**Comment by wslack** [comment] 2017-10-11 16:48
We think this is a config change in AWS. Will followup.

**Comment by jcscottiii** [comment] 2017-10-11 20:30
Information of what kind of redirect rules are possible for S3: http://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html#advanced-conditional-redirects

**Comment by jseppi** [comment] 2017-10-11 20:57
huh, so they don't want to _redirect_ to `/feed/index.xml` from `/feed/`, they want to actually have it served at `/feed/` if I understand correctly.

Maybe that can't be done with S3? Is there a way to specify _multiple_ default index file names in s3 bucket website hosting?

**Comment by wslack** [comment] 2017-10-11 21:16
> However, if you exclude the trailing slash from the preceding URL, Amazon S3 first looks for an object photos in the bucket. If the photos object is not found, then it searches for an index document, photos/index.html. If that document is found, Amazon S3 returns a 302 Found message and points to the photos/ key. For subsequent requests to photos/, Amazon S3 returns photos/index.html. If the index document is not found, Amazon S3 returns an error.

http://docs.aws.amazon.com/AmazonS3/latest/dev/IndexDocumentSupport.html

**Comment by wslack** [comment] 2017-10-11 21:21
I don't want to cause anything at /feed/ to always force a look at a feed/index.xml - Jeremy and I are trying to see what a file renaming accomplishes.

**Comment by wslack** [comment] 2017-10-11 21:28
Also looking at http://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html

**Comment by jeremyzilar** [comment] 2017-10-11 21:40
@jseppi Is this valid?
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/feed-redirect/feed/

It might work...

**Comment by jseppi** [comment] 2017-10-11 21:42
It is being served as `text/html`. I would think you'd want `application/xml` or some specific RSS-feed type. I'm not familiar with what your clients expect though.

**Comment by wslack** [comment] 2017-10-11 22:10
how is that configured, if not with suffix?

**Comment by jseppi** [comment] 2017-10-12 13:31
I think in S3 you can set an object's `content-type` (either via the web interface or through the api).

**Comment by wslack** [comment] 2017-10-12 17:15
The issue is that hugo wants to always amend a suffix to a file of content-type = XML.

**Comment by wslack** [comment] 2017-10-31 23:03
Just a note that I'm not sure of the next step on this yet. I feel like we figured out a workaround, maybe?

**Comment by wslack** [comment] 2018-01-04 00:50
What happened with this, @thisisdano?

**Comment by wslack** [comment] 2018-01-04 00:50
Moving to "backlog" for now.

**Comment by wslack** [comment] 2018-03-06 21:08
@jeremyzilar ok for us to close this?

**Comment by jeremyzilar** [comment] 2018-03-06 22:06
Yeah. 👍

**Closed by jeremyzilar** 2018-03-06 22:06 UTC
