### ISSUE TITLE
(Possible) Bug: Redis issue causes homepage to load slowly and prevents login

### ISSUE THREAD

**Issue by wslack** [18F/federalist#677] opened 2016-12-09 20:47 UTC

**Comment by jmhooper** [comment] 2016-12-09 21:53
This is the second time that this issue has occurred, so we're going to move from the assumption that it is a one-time problem.

Some background on this issue:

We use a redis instance as our session store. We believe this is happening because our app cannot connect to the redis instance to inspect the session for the request. In the time before the request for the session from redis times out, the site hangs. This also prevents auth from happening since we can't authenticate a session if we can't read/write from the session store.

There's 2 pieces of evidence that we use to support the hypothesis that the issue is with the connection to the session store:

0. In the past, scaling the app to 1 instance and using the in-memory session store instead of redis has solved the problem. Switching back to redis has caused it to re-appear.
0. The last time we saw this issue, we solved it by provisioning a new redis instance and switching over to that one

**Comment by jmhooper** [comment] 2016-12-09 21:59
Okay, it's starting to look like the issue described above is not what's actually happening. I just restarted the app with `cf restart federalist-staging` and it started working.

**Comment by jmhooper** [comment] 2016-12-13 19:16
We're looking at another incident of this bug today. I attempted to fix the site by restarting Federalist, but no luck.

**Comment by jmhooper** [comment] 2016-12-13 19:52
I scaled the app down to 1 instance and removed the Redis session store config (Sails will fallback to an in-memory store) here: https://github.com/18F/federalist/commit/1633da08e3570da480d8c9fbc46c801c51af4f94

That commit also short circuits CI to deploy to staging without needing to be merged. That build is here: https://travis-ci.org/18F/federalist/builds/183698496

That change was deployed successfully, and the app is now back up. That is consistent with the piece of evidence posted above and supports the thought that this is an issue with the redis instance:

> In the past, scaling the app to 1 instance and using the in-memory session store instead of redis has solved the problem. Switching back to redis has caused it to re-appear.

**Comment by wslack** [comment] 2016-12-23 18:41
We think this is fixed, but are not sure.

**Comment by wslack** [comment] 2016-12-23 18:42
Kubernetes had a defect that got rescheduled, but cloud.gov thinks they have resolved core issue.

**Comment by wslack** [comment] 2016-12-27 17:58
We're going to let this sit for a few weeks to see if it recurs.

**Comment by wslack** [comment] 2017-01-19 19:50
Haven't seen additional reports, closing

**Comment by wslack** [comment] 2017-02-17 17:47
Happened again yesterday!

**Comment by wslack** [comment] 2017-02-22 16:54
Happened again today on `federalist-prod`. We're wondering if there's any in-memory storage happening. @jmhooper is looking at this.

**Comment by wslack** [comment] 2017-03-03 20:49
no update yet

**Closed** 2017-03-20 20:10 UTC
Labels: bug
