### ISSUE TITLE
Make a list of Features to be tested 

### ISSUE THREAD

**Issue by bpdesigns** [18F/federalist#1721] opened 2018-03-22 14:39 UTC
#### Description of feature or bug

Make a list of Features to be tested. Federalist hasn't done user testing on many parts of the product. We should make a dent in that.

#### Definition of done

Spreadsheet with Feature descriptions, priority ranking and rational for rank

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] Collect features
- [ ] Decide how to rank them 
- [ ] Determine their rank

**Comment by wslack** [comment] 2018-03-22 15:44
Moving to Ready, but @bpdesigns and @qmanderson1 - would be good to specify what the purpose of the issue is. Something like "Federalist hasn't done user testing on many parts of the product. We should make a dent in that."

**Comment by bpdesigns** [comment] 2018-03-22 15:59
@wslack sounds good. Will address today

**Comment by bpdesigns** [comment] 2018-03-22 16:44
@ShannonBad I'll send you the spreadsheet we're working on. Please add anything you've already uncovered.

**Comment by bpdesigns** [comment] 2018-03-22 19:41
spreadsheet to collect information: https://docs.google.com/spreadsheets/d/1x91T57FNiBcbtWZQxjClRPV6L4fTdEgdSasFarm2KMI/edit#gid=0

**Comment by wslack** [comment] 2018-03-23 21:18
Paused for now as is; spreadsheet represents progress to date.

**Comment by wslack** [comment] 2018-05-17 19:41
Might be stuck until we have people to do this.

**Comment by wslack** [comment] 2018-05-17 19:43
Closing: step 1 for UX folks will be watching a use and ID'ing problem spots, not making lists of features

**Closed** 2018-05-17 19:43 UTC
Labels: ux
